### ISSUE TITLE
Not able to install addon from zip file

### ISSUE THREAD

**Issue by powermarcel10** [veldenb/plugin.video.blckbx-tv#1]
Hi! Thanks for creating this addon.

However, I'm not able to install it on my nvidia shield. Should it still work? I'm using Kodi 19.4.

Im only getting the error; not able to install addon from zip file.

Regards,
Marcel

**Comment by veldenb** [comment]
Hi,
can you try the v0.0.4 release? It should allow installation on more platforms.

**Comment by powermarcel10** [comment]
Thanks! I will try it ASAP and let you know.

**Comment by powermarcel10** [comment]
I can install it now. Thanks! 

However, items are not playing.. It keeps loading.. Also after a restart of Kodi. 

Also a few suggestions;

-Add date to video items to see when it was uploaded

-First time loading took a very long time.. Maybe its possible to update items in the background?

-Add video categories.

Cheers and thanks for your work!

**Comment by veldenb** [comment]
It's still a little rough indeed and needs some attention :)
I need to take a look at it to see if I can optimize it a bit.

**Comment by powermarcel10** [comment]
Allright, that would be nice.

But I cannot play any items right now. It keeps loading.. Any idea what the reason could be? On wich platform are you using kodi?

**Comment by veldenb** [comment]
Could you try the v0.0.5 version? It should be faster. After loading the video's once they should be cached and load faster.
Loading speed will also depend on the speed of your internet connection.

**Comment by veldenb** [comment]
Version v0.0.6 fixes some more issues and allows sorting. It also adds a full description of the video.
I currently use Kodi running LibreELEC on a Raspberry Pi4, but a Nvidia Shield should be powerful enough to run the plugin.

**Comment by powermarcel10** [comment]
Nice progress! I will test new version today and report back. 

Have a nice day!

**Comment by powermarcel10** [comment]
Tested new version but im still not able to play videos. It looks like it start, but than it keeps loading. After that Im not able to play any other video in kodi and have to restart Kodi. Any idea what is going wrong?

**Comment by veldenb** [comment]
I tried it on my Android TV and playing a video stalls like you describe. In version v0.1.0 I fixed some code hinting and now it plays on my Android TV. Does the fix also work for your Shield?

**Comment by powermarcel10** [comment]
Hi!

Still same problem. A couple of times the video started playing for a couple of seconds, and than the screen goes black and I had to restart Kodi.

Loading the addon is a lot faster now BTW.

**Comment by veldenb** [comment]
The only thing I can think of is old cache, on my phone and android tv the plugin works.
You could try to uninstall the plugin and remove settings and related files with it, after that reboot and reinstall the plugin.

**Comment by powermarcel10** [comment]
Hmmm, too bad. Tried that already. I have no idea what is going wrong. If you have any ideas.. I'm happy to test in the future.

Anyway, thanks for your support.

**Comment by powermarcel10** [comment]
Hi! Me again.. Im having a question.. 

It seems that the nvidia shield is the reason im not able to use this addon.. I tried another addon called rumble where the videos of blckbx also can be watched. And that addon had the same problem. Not able to play. 

However, on my chromebook and android phone, your addon and the rumble addon are working fine.

I tried a fresh kodi install using the same version as on my phone, but still the same problem. So im trying to figure out what is causing this..

Can you tell me on wich Android tv device you are running kodi and this addon?

Cheers,
Marcel

**Comment by veldenb** [comment]
Hi @powermarcel10!

The TV is an Philips 55OLED705/12 running Android 11. My phone is a Samsung also running Android 11.

**Comment by powermarcel10** [comment]
Thanks! I had more issues with my nvidia shield since the update to android 11. Yesterday I downgraded my shield and it runs a lot better and faster now.. And.. Your addon is finally working now on my Shield! 

So, thanks for your support.
